# Captured from the live Argo CD Application on 2026-10-06.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-secrets
    helm:
      values: |
        installCRDs: true
        crds:
          install: true
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.11.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - Replace=true
