apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backup
  namespace: {{ .Values.vault.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.backup.size }}
